data:
  dataset: 'MNIST'
  batch_size: 64
  val_split: 0.3

model:
  model: "convVAE" #클래스명
  latent_dim: 20
  hidden_dims: [32, 64, 128]
  learning_rate: 0.001
  epochs: 3

log:
  model_save_dir: 'outputs/models/mnist_convvae.pth'
  image_save_dir: 'outputs/image/'
