data:
  dataset: 'MNIST'
  batch_size: 64
  val_split: 0.3

model:
  model: "VAE" #클래스명
  latent_dim: 20
  hidden_dims: [256, 128]
  learning_rate: 0.0001
  epochs: 20

log:
  model_save_dir: 'outputs/models/mnist_vae.pth'
  image_save_dir: 'outputs/image/'